### ISSUE TITLE
Once ingame I cannot 'select' DLSS

### ISSUE THREAD

**Issue by DonSolohh** [P4TOLINO06/FSR3.0-Mod-Setup-Utility#8]
Once I select DLSS here 
![{70D3502B-CBCA-47E8-A665-653FDE85B38B}](https://github.com/user-attachments/assets/2828b8aa-2571-49d3-b5c8-d57d11d21f62)

it always reverts back to FSR 3.1.0

DLSS is an option but when I apply, it doesn't work.

In the 'ingame' options it does show DLSS/DLAA and FSR3 FrameGen/DLSS framegen as an option but I'm confused overall on how this works.

You have no true tutorial for Stalker 2, but I feel like something is wrong. (I installed the DLSS/FSR FGEN mod)

Ingame these are my settings.

![{9A18AE5F-0754-4860-953E-80D736C56B11}](https://github.com/user-attachments/assets/aa95aeea-2763-4890-996f-71375332d6c1)

but what confuses me is if it's not letting me choose DLSS in the upscaler, something is wrong - I'm not even sure which is getting superseded.

**Comment by P4TOLINO06** [comment]
If you're talking about Stalker 2, the game has received some updates since
the mod was added (DLSS (Only Nvidia)), which might be the issue.

Stalker 2 only has two mods: DLSS FG (Only RTX) and Other Mods (which
installs Anti-Stutter and some other mods). If you have installed any FSR
3.1.2/DLSS mod, it probably won't work with Stalker 2.

Em qua., 11 de dez. de 2024 às 12:53, DonSolohh ***@***.***>
escreveu:

**Comment by DonSolohh** [comment]
I believe I chose DLSS FG only - but you're saying I can only have ONE of those mods installed at a single time or they'll conflict or something?

**Comment by DonSolohh** [comment]
Also in your utility [enhanced] -- these options are somewhat confusing (as well as the frame gen method tab) .. as you have some of those under 'initial settings'
